#!/bin/bash
# Copyright (C) 2022 Kevin Pham
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source=$1

# Passed in from concourse via stdin, with the format { "params": { ... }, "source": { ... } }
# As mentioned here: https://concourse-ci.org/implementing-resource-types.html#resource-out
# But will contain values you provide as part of the step.
payload="$(cat <&0)"

# Fetch and set DISCORD_WEBHOOK env is value was provided. This allows for the
# webhook order of priority to take effect. Note that the only option not
# supported remaining is the ".webhook" file.
export DISCORD_WEBHOOK=`jq -r '.source.DISCORD_WEBHOOK' <<< "$payload"`

# Set the default params list to an empty string.
params=""

# List of all variables expected
# ==========================================================================
# Because I'm "lazy" and don't like hardcoding things, I'll grab the options
# from the default discord.sh help prompt. If there are new options in the
# future.. then it should "just work".
variables=`/discord.sh/discord.sh --help \
    # Filter lines containing the options. I checked, it seems all have the long form.
    | grep -- -- \
    # Remove all characters before the -- including itself, and everything after a space or =
    | sed 's/^[^-]*--//;s/[ =].*//' \
    # Sort the results
    | sort \
    # So we can only keep the unique results
    | uniq`

for field in "${variables[@]}"; do
    # Grab the field using jq
    raw=`jq ".params.\"$field\"" <<< "$payload"`
    # Interpolate any bash variables
    value=`eval "echo $raw"`

    # echo "$field: $value" # debugging~

    # Build the argument/param list for the discord.sh call
    if [[ "$value" != "null" ]] ; then
        params="${params} --${field}=\"${value}\""
    fi
done

# Execute the command
eval "/discord.sh/discord.sh $params"

# Example:
# /discord.sh/discord.sh --username "CI/CD" --text="$text"

# Is this required? Probably..
jq -n "{version: {}}" >&3
